### ISSUE TITLE
链接坏了

### ISSUE THREAD

**Issue by dawncold** [BioniCosmos/blog#1]
404了

url: https://moecm.com/tproxy-with-v2ray-on-rpi
> 本文已废弃，重构后的最新版本请移步 [Xray 配置透明代理](/v2ray/xray-transparent-proxy/)，感谢您的配合。

**Comment by BioniCosmos** [comment]
Resolved in <https://github.com/BioniCosmos/blog/commit/560929a1103a4feefdf9083341d19e6ea2798839>
